export const HQ_LOCALITIES_DIRECTORY: Record<string, string[]> = {
  bhopal: [
    'Arera Colony',
    'MP Nagar Zone 1',
    'MP Nagar Zone 2',
    'New Market (TT Nagar)',
    'Kolar Road',
    'Hoshangabad Road',
    'Indrapuri (BHEL)',
    'Shahpura',
    'Bairagarh (Sant Hirdaram Nagar)',
    'Hamidia Road',
    'Chuna Bhatti',
    'Ayodhya Bypass',
    'Govindpura Industrial Area',
    'Gulmohar Colony',
    'Peer Gate / City Area',
    'Karond Bypass',
    'Malviya Nagar',
    'Jahangirabad',
    'Awadhpuri',
    'Nehru Nagar',
    'Ashoka Garden',
    'Bhadbhada Road',
  ],
  indore: [
    'Vijay Nagar',
    'Old Palasia',
    'New Palasia',
    'Geeta Bhawan (AB Road)',
    'Sapna Sangeeta Road',
    'Bhawarkua Square',
    'Dawa Bazar (South Tukoganj)',
    'Rajwada & Sarafa',
    'LIG Colony',
    'Annapurna Road',
    'Sudama Nagar',
    'Rau & Silicon City',
    'Pardesipura',
    'Chhavani',
    'Navlakha',
    'Tilak Nagar',
    'MG Road & Treasure Island',
    'Kanadia Road',
    'Mahalaxmi Nagar',
    'Khandwa Road',
  ],
  jabalpur: [
    'Wright Town',
    'Napier Town',
    'Civil Lines',
    'Gorakhpur',
    'Madan Mahal',
    'Russell Chowk',
    'Adhartal',
    'Ganjipura / Supermarket',
    'Garha & Medical College Area',
    'Vijay Nagar (Jabalpur)',
    'Ranjhi',
    'Dhanvantari Nagar',
  ],
  gwalior: [
    'Lashkar',
    'Morar',
    'City Center',
    'Phoolbagh',
    'Jayendraganj',
    'Naya Bazar',
    'Thatipur',
    'Maharaj Bada',
    'Hazira',
    'Deen Dayal Nagar',
  ],
  raipur: [
    'Pandri (Cloth & Dawa Market)',
    'Shankar Nagar',
    'Devendra Nagar',
    'Telibandha / Marine Drive',
    'Tatibandh (AIIMS Area)',
    'Fafadih',
    'Samta Colony',
    'Jaistambh Chowk',
    'Gudhiyari',
    'Pachpedi Naka',
  ],
  ujjain: [
    'Freeganj',
    'Tower Chowk',
    'Nanakheda',
    'Dewas Road',
    'Mahakal Commercial Belt',
    'Agar Road',
    'Sethi Nagar',
    'Kshirsagar',
  ],
  sagar: [
    'Civil Lines (Sagar)',
    'Katra Bazar',
    'Tilli & Medical College',
    'Makronia',
    'Gopal Ganj',
    'Cantt Area',
  ],
  rewa: [
    'Civil Lines (Rewa)',
    'College Road',
    'Venkat Road',
    'Bodbagh',
    'Sirmour Chowk',
    'Dhekaha',
  ],
  bilaspur: [
    'Vyapar Vihar',
    'Link Road',
    'Telipara',
    'Torwa',
    'Rajendra Nagar',
    'Mangla Chowk',
  ],
  nagpur: [
    'Dharampeth',
    'Ramdaspeth',
    'Dhantoli (Hospital Belt)',
    'Sitabuldi',
    'Gandhibagh (Dawa Market)',
    'Sadar',
    'Wardha Road',
    'Manewada',
  ],
};

export const COMMON_BEAT_PATTERNS = [
  'Sector 1 - Doctor Cluster',
  'Sector 2 - Chemist & Nursing Homes',
  'Main Market Route',
  'Hospital & Clinic Belt',
  'Commercial Complex Route',
  'Morning Call Belt',
  'Evening OPD Route',
  'Highway Doctor Cluster',
];

export function getDirectoryLocalities(contextLocation: string): string[] {
  if (!contextLocation) return [];
  const normalized = contextLocation.toLowerCase();
  for (const [cityKey, list] of Object.entries(HQ_LOCALITIES_DIRECTORY)) {
    if (normalized.includes(cityKey)) {
      return list;
    }
  }
  return [];
}
