export type Gender = 'MALE' | 'FEMALE' | 'OTHER';
export type MaritalStatus = 'SINGLE' | 'MARRIED' | 'DIVORCED' | 'WIDOWED';
export type AccountType = 'SAVINGS' | 'CURRENT' | 'SALARY';
export type EmployeeStatus = 'ACTIVE' | 'RESIGNED' | 'TERMINATED' | 'SUSPENDED' | 'ON_LEAVE' | 'ABSCONDING';
export type EmploymentStatus = EmployeeStatus;

export interface Employee {
  id: string;
  empCode: string;
  firstName: string;
  middleName?: string;
  lastName: string;
  name?: string;
  fullName?: string;
  code?: string;
  dateOfBirth?: string;
  gender: Gender;
  maritalStatus: MaritalStatus;
  bloodGroup?: string;
  mobile: string;
  alternateMobile?: string;
  email?: string;
  emergencyContactName?: string;
  emergencyContactNo?: string;
  emergencyContactRelation?: string;
  currentAddress?: string;
  permanentAddress?: string;
  fatherName?: string;
  fatherOccupation?: string;
  motherName?: string;
  spouseName?: string;
  numberOfChildren?: number;
  qualification?: string;
  highestQualification?: string;
  specialization?: string;
  university?: string;
  instituteName?: string;
  passingYear?: string;
  aadhaarNumber?: string;
  aadharNumber?: string;
  panNumber?: string;
  passportNumber?: string;
  passportExpiry?: string;
  drivingLicenseNumber?: string;
  drivingLicenseExpiry?: string;
  identityDocs?: string[];
  bankName?: string;
  accountNumber?: string;
  ifscCode?: string;
  accountType: AccountType;
  branchName?: string;
  joiningDate?: string;
  department?: string;
  designation?: string;
  status: EmployeeStatus;
  employeeStatus?: EmployeeStatus;
  isActive?: boolean;
  divisionId?: string;
  hqId?: string;
  managerId?: string;
  areaId?: string;
  createdAt?: string;
  updatedAt?: string;
}
