import React, { useState } from 'react';
import { Head } from '../components/Head';
import { Badge } from '../components/Badge';
import { zones, states, hqs, areas, beats } from '../data';

export function Geography() {
  const [tab, setTab] = useState<'Zone' | 'State' | 'HQ' | 'Area' | 'Beat'>(
    'Zone'
  );

  const map: any = { Zone: zones, State: states, HQ: hqs, Area: areas, Beat: beats };

  const parent = (x: any) =>
    tab === 'State'
      ? zones.find((z) => z.id === x.zoneId)?.name
      : tab === 'HQ'
      ? states.find((s) => s.id === x.stateId)?.name
      : tab === 'Area'
      ? hqs.find((h) => h.id === x.hqId)?.name
      : tab === 'Beat'
      ? areas.find((a) => a.id === x.areaId)?.name
      : '—';

  return (
    <>
      <Head
        title="Geography Master"
        sub="Zone → State → HQ → Area → Beat"
        action={<button className="primary">＋ Add {tab}</button>}
      />
      <div className="tabs">
        {(['Zone', 'State', 'HQ', 'Area', 'Beat'] as const).map((t) => (
          <button
            className={tab === t ? 'on' : ''}
            onClick={() => setTab(t)}
            key={t}
          >
            {t}
          </button>
        ))}
      </div>
      <div className="panel table">
        <table>
          <thead>
            <tr>
              <th>Code</th>
              <th>Name</th>
              <th>Parent</th>
              <th>Status</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {map[tab].map((x: any) => (
              <tr key={x.id}>
                <td>
                  <b>{x.code}</b>
                </td>
                <td>{x.name}</td>
                <td>{parent(x)}</td>
                <td>
                  <Badge v={x.isActive ? 'ACTIVE' : 'INACTIVE'} />
                </td>
                <td>
                  <button className="link">Edit</button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <div className="note">
        <b>Backend rule:</b> HQ / Area / Beat codes are not generated by this Web
        UI. When API integration is added, code generation belongs in the
        Worker/MasterDataService.
      </div>
    </>
  );
}
