ALTER TABLE users ADD COLUMN manager_id TEXT REFERENCES users(id);
ALTER TABLE users ADD COLUMN asm_id TEXT REFERENCES users(id);
ALTER TABLE users ADD COLUMN rsm_id TEXT REFERENCES users(id);
ALTER TABLE users ADD COLUMN zsm_id TEXT REFERENCES users(id);
ALTER TABLE users ADD COLUMN vp_id TEXT REFERENCES users(id);
ALTER TABLE users ADD COLUMN admin_id TEXT REFERENCES users(id);
ALTER TABLE users ADD COLUMN hierarchy_status TEXT DEFAULT 'ACTIVE';
