import { z } from 'zod';
import { baseEntity } from './base';

export const EmployeeSchema = baseEntity.extend({
  emp_code: z.string().optional().nullable(),
  first_name: z.string().min(1, 'first_name is required'),
  middle_name: z.string().optional().nullable(),
  last_name: z.string().min(1, 'last_name is required'),
  date_of_birth: z.string().optional().nullable(),
  gender: z.string().optional().nullable(),
  blood_group: z.string().optional().nullable(),
  marital_status: z.string().optional().nullable(),
  mobile: z.string().min(1, 'mobile is required'),
  alternate_mobile: z.string().optional().nullable(),
  email: z.string().optional().nullable(),
  emergency_contact_name: z.string().optional().nullable(),
  emergency_contact_no: z.string().optional().nullable(),
  emergency_contact_relation: z.string().optional().nullable(),
  current_address: z.string().optional().nullable(),
  permanent_address: z.string().optional().nullable(),
  father_name: z.string().optional().nullable(),
  father_occupation: z.string().optional().nullable(),
  mother_name: z.string().optional().nullable(),
  spouse_name: z.string().optional().nullable(),
  number_of_children: z.number().optional().default(0),
  highest_qualification: z.string().optional().nullable(),
  specialization: z.string().optional().nullable(),
  institute_name: z.string().optional().nullable(),
  passing_year: z.string().optional().nullable(),
  aadhar_number: z.string().optional().nullable(),
  pan_number: z.string().optional().nullable(),
  passport_number: z.string().optional().nullable(),
  passport_expiry: z.string().optional().nullable(),
  driving_license_number: z.string().optional().nullable(),
  driving_license_expiry: z.string().optional().nullable(),
  identity_docs: z.union([z.string(), z.array(z.any())]).optional().nullable(),
  bank_name: z.string().optional().nullable(),
  account_number: z.string().optional().nullable(),
  ifsc_code: z.string().optional().nullable(),
  account_type: z.string().optional().nullable(),
  employee_status: z.string().optional().default('ACTIVE'),
  is_active: z.union([z.boolean(), z.number()]).transform(v => (v === true || v === 1 ? 1 : 0)).optional().default(1),
  created_at: z.string().optional().nullable(),
  created_by: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  updated_by: z.string().optional().nullable(),
});
