import { z } from 'zod';
import { baseEntity } from './base';

export const HqSchema = baseEntity.extend({
  hq_name: z.string().min(1).max(100).transform(val => val.trim()),
  hq_code: z.string().optional().nullable().transform(val => val ? val.trim().toUpperCase() : null),
  state_id: z.string().optional().nullable(),
  zone_id: z.string().optional().nullable(),
  division_id: z.string().optional().nullable(),
  hq_type: z.string().optional().default('HQ'),
  city: z.string().optional().nullable(),
  district: z.string().optional().nullable(),
  pin_code: z.string().length(6, "PIN must be 6 digits").optional().nullable(),
  latitude: z.number().optional().nullable(),
  longitude: z.number().optional().nullable(),
  state_code: z.string().optional().nullable(),
  is_pool_hq: z.union([z.boolean(), z.number()]).transform(v => (v === true || v === 1 ? 1 : 0)).optional().default(0),
  parent_pool_hq_id: z.string().optional().nullable(),
  is_super_hq: z.union([z.boolean(), z.number()]).transform(v => (v === true || v === 1 ? 1 : 0)).optional().default(0),
  display_order: z.number().optional().default(0),
  description: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  created_by: z.string().optional().nullable(),
  updated_by: z.string().optional().nullable(),
  deleted_at: z.string().optional().nullable(),
  deleted_by: z.string().optional().nullable(),
});

export const AreaSchema = baseEntity.extend({
  area_name: z.string().min(1).transform(val => val.trim()),
  area_code: z.string().optional().nullable().transform(val => val ? val.trim().toUpperCase() : null),
  territory_type: z.string().optional().nullable(),
  hq_id: z.string().min(1),
  zone_id: z.string().optional().nullable(),
  state_id: z.string().optional().nullable(),
  division_id: z.string().optional().nullable(),
  default_travel_mode: z.string().optional().nullable(),
  both_side_allowed: z.union([z.boolean(), z.number()]).transform(v => (v === false || v === 0 ? 0 : 1)).optional().default(1),
  display_order: z.number().optional().default(0),
  description: z.string().optional().nullable(),
  travel_mode: z.string().optional().default('TWO_SIDE'),
  created_at: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  created_by: z.string().optional().nullable(),
  updated_by: z.string().optional().nullable(),
  deleted_at: z.string().optional().nullable(),
  deleted_by: z.string().optional().nullable(),
});

export const BeatSchema = baseEntity.extend({
  beat_name: z.string().min(1).transform(val => val.trim()),
  beat_code: z.string().optional().nullable().transform(val => val ? val.trim().toUpperCase() : null),
  beat_type: z.string().optional().default('CORE'),
  area_id: z.string().min(1),
  hq_id: z.string().optional().nullable(),
  zone_id: z.string().optional().nullable(),
  state_id: z.string().optional().nullable(),
  division_id: z.string().optional().nullable(),
  display_order: z.number().optional().default(0),
  description: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  created_by: z.string().optional().nullable(),
  updated_by: z.string().optional().nullable(),
  deleted_at: z.string().optional().nullable(),
  deleted_by: z.string().optional().nullable(),
});

export const StateSchema = baseEntity.extend({
  state_code: z.string().optional().nullable().transform(val => val ? val.trim().toUpperCase() : null),
  state_name: z.string().min(1).transform(val => val.trim()),
  description: z.string().optional().nullable(),
  display_order: z.number().optional().default(0),
  zone_id: z.string().min(1),
  division_id: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  created_by: z.string().optional().nullable(),
  updated_by: z.string().optional().nullable(),
  deleted_at: z.string().optional().nullable(),
  deleted_by: z.string().optional().nullable(),
});

export const ZoneSchema = baseEntity.extend({
  zone_code: z.string().optional().nullable().transform(val => val ? val.trim().toUpperCase() : null),
  name: z.string().min(1).transform(val => val.trim()),
  description: z.string().optional().nullable(),
  head_user_id: z.string().optional().nullable(),
  head_user_name: z.string().optional().nullable(),
  division_id: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  created_by: z.string().optional().nullable(),
  updated_by: z.string().optional().nullable(),
  deleted_at: z.string().optional().nullable(),
  deleted_by: z.string().optional().nullable(),
});
