import { z } from 'zod';
import { baseEntity } from './base';

export const SalesTargetSchema = baseEntity.extend({
  hq_id: z.string().min(1, 'hq_id is required'),
  hq_name: z.string().optional().nullable(),
  fy: z.string().min(1, 'fy is required'),
  product_id: z.string().min(1, 'product_id is required'),
  product_name: z.string().optional().nullable(),
  apr: z.number().optional().default(0),
  may: z.number().optional().default(0),
  jun: z.number().optional().default(0),
  jul: z.number().optional().default(0),
  aug: z.number().optional().default(0),
  sep: z.number().optional().default(0),
  oct: z.number().optional().default(0),
  nov: z.number().optional().default(0),
  dec: z.number().optional().default(0),
  jan: z.number().optional().default(0),
  feb: z.number().optional().default(0),
  mar: z.number().optional().default(0),
});

export const SalesEntrySchema = baseEntity.extend({
  type: z.string().min(1),
  employee_id: z.string().optional().nullable(),
  employee_name: z.string().optional().nullable(),
  target_id: z.string().min(1),
  target_name: z.string().min(1),
  month_year: z.string().optional().nullable(),
  total_amount: z.number().optional().default(0),
  items: z.union([z.string(), z.array(z.any())]).optional().nullable(),
  date: z.string().optional().nullable(),
  employee_hq_id: z.string().optional().nullable(),
  target_hq_id: z.string().optional().nullable(),
  target_hq_name: z.string().optional().nullable(),
  target_area_id: z.string().optional().nullable(),
  target_area_name: z.string().optional().nullable(),
  is_active: z.number().optional().default(1),
  created_at: z.string().optional().nullable(),
  created_by: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  updated_by: z.string().optional().nullable(),
});

export const LeaveAllocationSchema = baseEntity.extend({
  employee_id: z.string().min(1, 'employee_id is required'),
  employee_name: z.string().optional().nullable(),
  designation: z.string().optional().nullable(),
  hq_name: z.string().optional().nullable(),
  year: z.string().min(1, 'year is required'),
  balance_cl: z.number().optional().default(0),
  balance_sl: z.number().optional().default(0),
  balance_pl: z.number().optional().default(0),
  is_active: z.number().optional().default(1),
  created_at: z.string().optional().nullable(),
  created_by: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  updated_by: z.string().optional().nullable(),
});

export const DaRateSchema = baseEntity.extend({
  role: z.string().min(1, 'role is required'),
  city_type: z.string().default('HQ'),
  amount: z.union([z.number(), z.string().transform(Number)]).default(0),
  effective_from: z.string().optional().nullable(),
  is_active: z.union([z.boolean(), z.number()]).transform(v => (v === true || v === 1 ? 1 : 0)).optional().default(1),
  fare_type: z.string().optional().nullable(),
  km_rate_0_199: z.union([z.number(), z.string().transform(Number)]).optional().nullable(),
  km_rate_200_299: z.union([z.number(), z.string().transform(Number)]).optional().nullable(),
  travel_mode_299_599: z.string().optional().nullable(),
  travel_mode_600_plus: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  created_by: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  updated_by: z.string().optional().nullable(),
});

export const LeaveApplicationSchema = baseEntity.extend({
  employee_id: z.string().min(1, 'employee_id is required'),
  employee_name: z.string().optional().nullable(),
  leave_type: z.enum(['CL', 'SL', 'PL', 'LWP']),
  from_date: z.string().min(1, 'from_date is required'),
  to_date: z.string().min(1, 'to_date is required'),
  num_days: z.number().min(0.5, 'num_days must be at least 0.5'),
  reason: z.string().optional().nullable(),
  emergency_contact: z.string().optional().nullable(),
  status: z.string().optional().default('APPROVED'),
  approved_by: z.string().optional().nullable(),
  approved_at: z.string().optional().nullable(),
  fy: z.string().optional().nullable(),
  hq_id: z.string().optional().nullable(),
  login_id: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  created_by: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  updated_by: z.string().optional().nullable(),
  deleted_at: z.string().optional().nullable(),
  deleted_by: z.string().optional().nullable(),
});

export const DcrEntrySchema = baseEntity.extend({
  user_id: z.string().optional().nullable(),
  employee_id: z.string().min(1, 'employee_id is required'),
  date: z.string().min(1, 'date is required'),
  work_type: z.string().optional().nullable(),
  work_with_mode: z.string().optional().nullable(),
  area_type: z.string().optional().nullable(),
  employee_name: z.string().optional().nullable(),
  employee_role: z.string().optional().nullable(),
  employee_hq_id: z.string().optional().nullable(),
  employee_hq_name: z.string().optional().nullable(),
  working_area_ids: z.union([z.string(), z.array(z.any())]).optional().nullable(),
  joint_with_ids: z.union([z.string(), z.array(z.any())]).optional().nullable(),
  from_id: z.string().optional().nullable(),
  to_id: z.string().optional().nullable(),
  both_side_allowed: z.union([z.boolean(), z.number()]).transform(v => (v === true || v === 1 ? 1 : 0)).optional().default(0),
  beat_id: z.string().optional().nullable(),
  ta_amount: z.number().optional().default(0),
  da_amount: z.number().optional().default(0),
  misc_amount: z.number().optional().default(0),
  misc_note: z.string().optional().nullable(),
  day_remarks: z.string().optional().nullable(),
  is_submitted: z.union([z.boolean(), z.number()]).transform(v => (v === true || v === 1 ? 1 : 0)).optional().default(0),
  submitted_at: z.string().optional().nullable(),
  plan_at: z.string().optional().nullable(),
  dr_calls: z.union([z.string(), z.array(z.any())]).optional().nullable(),
  chemist_calls: z.union([z.string(), z.array(z.any())]).optional().nullable(),
  stockist_calls: z.union([z.string(), z.array(z.any())]).optional().nullable(),
  local_id: z.string().optional().nullable(),
  server_id: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  created_by: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  updated_by: z.string().optional().nullable(),
  deleted_at: z.string().optional().nullable(),
  deleted_by: z.string().optional().nullable(),
});

export const SfcRateSchema = baseEntity.extend({
  from_node_type: z.enum(['SUPER_HQ', 'HQ', 'AREA']).optional().default('HQ'),
  from_node_id: z.string().optional().nullable(),
  from_node_name: z.string().optional().nullable(),
  to_node_type: z.enum(['HQ', 'AREA']).optional().default('AREA'),
  to_node_id: z.string().optional().nullable(),
  to_node_name: z.string().optional().nullable(),
  from_hq_id: z.string().optional().nullable(),
  from_hq_name: z.string().optional().nullable(),
  to_area_id: z.string().optional().nullable(),
  to_area_name: z.string().optional().nullable(),
  travel_type: z.enum(['LOCAL_HQ', 'EX_HQ', 'OUTSTATION']).default('EX_HQ'),
  distance_km: z.number().min(0, 'distance_km must be non-negative'),
  round_trip_km: z.number().optional().nullable(),
  rate_per_km: z.number().optional().nullable(),
  approved_fare: z.number().min(0, 'approved_fare must be non-negative'),
  effective_from: z.string().optional().nullable(),
  is_active: z.union([z.boolean(), z.number()]).transform(v => (v === true || v === 1 ? 1 : 0)).optional().default(1),
  created_at: z.string().optional().nullable(),
  created_by: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  updated_by: z.string().optional().nullable(),
});
