export const QUALIFICATION_OPTIONS = [
  'MBBS',
  'MD',
  'MD (DVL)',
  'DDVL',
  'DVD',
  'DDV',
  'DNB (DVL)',
  'PGDC (Cosmetology)',
  'FAM (Aesthetic Med)',
  'MS',
  'DNB',
  'DM',
  'MCh',
  'BAMS',
  'BHMS',
  'BUMS',
  'BDS',
  'MDS',
  'DGO',
  'DCH',
  'Diploma',
  'Other',
];

export const SPECIALITY_OPTIONS = [
  'Dermatologist',
  'Cosmetologist',
  'Trichologist',
  'General Physician (GP)',
  'Aesthetic Physician',
  'Cardiologist',
  'Pediatrician',
  'Gynecologist',
  'Orthopedic Surgeon',
  'ENT Specialist',
  'Neurologist',
  'Gastroenterologist',
  'Diabetologist',
  'Dentist',
  'Ayurvedic Practitioner',
  'Homeopathic Practitioner',
  'Other',
];

export const INDIAN_STATES = [
  'Madhya Pradesh',
  'Maharashtra',
  'Uttar Pradesh',
  'Rajasthan',
  'Gujarat',
  'Chhattisgarh',
  'Delhi',
  'Bihar',
  'Karnataka',
  'Tamil Nadu',
  'Telangana',
  'Andhra Pradesh',
  'West Bengal',
  'Punjab',
  'Haryana',
  'Kerala',
  'Odisha',
  'Assam',
  'Jharkhand',
  'Uttarakhand',
  'Himachal Pradesh',
  'Goa',
  'Other',
];
